// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle observation emitted by the embedded Codex TUI for the native
 * Marathon recovery seam. The TUI sends this only after its existing pending
 * synthetic turn is created, dispatched, or completed. It carries metadata,
 * never prompt text or credentials.
 */
export type CodexMarathonRecoveryLifecycleNotification = {
/**
 * One of `recovery_parked`, `recovery_started`, or
 * `recovery_completed`.
 */
eventType: string, recoveryId: string, threadId: string | null, turnId: string | null, sourceAccountId: string | null, reason: string | null, outcome: string | null, errorCode: string | null, };
