// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result sent by the TUI after applying a Marathon release command to the
 * session-owned pending recovery state.
 *
 * The result is intentionally string-shaped at this upstream protocol seam;
 * the Marathon adapter maps it to its typed release outcome without making
 * the Codex app-server protocol depend on Marathon crates.
 */
export type CodexMarathonRecoveryReleaseResultNotification = { recoveryId: string, threadId: string | null, transitionId: string, expectedGeneration: number, outcome: string, errorCode: string | null, errorMessage: string | null, };
