// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Internal command from the embedded Marathon authority to the Codex TUI.
 *
 * The TUI already owns the parked `UsageLimitExceeded` continuation.  This
 * notification is only an authorization hand-off; it does not carry prompt
 * text and must never be interpreted as a request to create another turn.
 */
export type CodexMarathonRecoveryReleaseNotification = { recoveryId: string, threadId: string | null, transitionId: string, expectedGeneration: number, };
