// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of changing the native Marathon enabled state.
 */
export type MarathonEnabledSetResponse = { enabled: boolean, };
