// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarathonAutoResetExpiryJob } from "./MarathonAutoResetExpiryJob";

/**
 * Shared expiry state embedded in the overall Marathon status.
 */
export type MarathonAutoResetExpiryStatus = { enabled: boolean, effectiveEnabled: boolean, executorAvailable: boolean, jobs: Array<MarathonAutoResetExpiryJob>, jobsTruncated: boolean, nextAttemptAt: string | null, };
