// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Secret-free state of one durable expiry job.
 */
export type MarathonAutoResetExpiryJob = { jobId: string, accountId: string, creditId: string, state: string, expiresAt: string, nextAttemptAt: string | null, attempt: bigint, diagnosticCode: string | null, };
