// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request a manual switch to an account id or registered alias.
 */
export type MarathonSwitchParams = { target: string, };
