// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarathonSwitchOutcome } from "./MarathonSwitchOutcome";

/**
 * Secret-free result of a manual account switch.
 */
export type MarathonSwitchResponse = { accountId: string | null, outcome: MarathonSwitchOutcome, authGeneration: bigint, activeTurnCount: number, reason: string | null, };
