// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configure use of banked reset credits fifteen minutes before their expiry.
 */
export type MarathonAutoResetExpirySetParams = { enabled: boolean, };
