// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Checkpoint an already-saved current account through native AuthManager.
 * Optimistic identity/generation binding prevents saving a different account
 * after a status/selection race. No snapshot or passphrase crosses this API.
 */
export type MarathonCheckpointParams = { expectedAccountId: string, expectedAuthGeneration: bigint, };
