// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarathonAutoResetExpiryJob } from "./MarathonAutoResetExpiryJob";

/**
 * Daemon-authoritative expiry state. Enabling this policy is independent of
 * the zero-weekly-quota policy; the Marathon master switch gates execution.
 */
export type MarathonAutoResetExpiryStatusResponse = { enabled: boolean, effectiveEnabled: boolean, executorAvailable: boolean, jobs: Array<MarathonAutoResetExpiryJob>, jobsTruncated: boolean, nextAttemptAt: string | null, };
