// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enable or disable automatic use of a provider reset action when every
 * eligible managed account has zero weekly quota.
 */
export type MarathonAutoResetSetParams = { enabled: boolean, };
