// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarathonAccount } from "./MarathonAccount";

/**
 * Status of the in-process Marathon account manager.
 *
 * This type intentionally contains identity and lifecycle metadata only. It
 * must never grow fields containing auth snapshots or token material.
 */
export type MarathonStatusResponse = { enabled: boolean, activeAccountId: string | null, currentAccountId: string | null, authGeneration: bigint, activeTurnCount: number, accounts: Array<MarathonAccount>, autoResetEnabled: boolean, autoResetPhase: string, autoResetLastError: string | null, };
