// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capture the currently authenticated Codex identity in the Marathon vault.
 *
 * The auth document is read only through Codex's native AuthManager. Clients
 * never send token material to this request.
 */
export type MarathonImportParams = { alias: string, };
