// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Secret-free result of importing the current native Codex identity.
 */
export type MarathonImportResponse = { accountId: string, alias: string, active: boolean, replaced: boolean, };
