// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Secret-free view of one account managed by the native Marathon service.
 */
export type MarathonAccount = { accountId: string, alias: string, active: boolean, credentialPresent: boolean, credentialHealth: string,
/**
 * Last native provider observation for the weekly/long quota window.
 * `null` means the provider has not supplied a weekly window yet.
 */
weeklyQuotaRemainingPercent: number | null,
/**
 * Whether the provider reported an immediate quota-reset action for this
 * account. This is capability metadata, never an inferred timestamp.
 */
resetActionAvailable: boolean, };
