// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexMarathonRecoveryLifecycleNotification } from "./v2/CodexMarathonRecoveryLifecycleNotification";
import type { CodexMarathonRecoveryReleaseResultNotification } from "./v2/CodexMarathonRecoveryReleaseResultNotification";

export type ClientNotification = { "method": "initialized" } | { "method": "codexMarathonRecoveryLifecycle", "params": CodexMarathonRecoveryLifecycleNotification } | { "method": "codexMarathonRecoveryReleaseResult", "params": CodexMarathonRecoveryReleaseResultNotification };
